### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by spetsnaz84** [jwillemsen/saj_collector#1]
Dear Johnny,

I have a SAJ 3KM solar inverter.
I have noticed you have this interesting project to connect to the inverter. I wonder how you connect to the inverter. I only have an RS232 module. Did you buy an extra ethernet or wifi module to connect ? I am puzzled to figure out the right RS232 parameters.

Could you give me some more details ?

Thanks !

Paul

**Comment by jwillemsen** [comment]
I have a Sununo-TL4KA which has by default a wired ethernet connection which I use to poll the converter. As far as I can see the 3KM has an optional wifi module, that could be used to connect. Sorting out the RS232 parameters will take a lot of work, don't have free time available for that.

**Comment by spetsnaz84** [comment]
Yeah, I know but they wanted to charge me 100 euro to buy the WiFi module so I thought I just read it out over RS232 instead.
Thanks for your reply.

**Comment by jwillemsen** [comment]
No experience with their rs232 support
