### ISSUE TITLE
saj_output_collector off by factor 10

### ISSUE THREAD

**Issue by degerrit** [jwillemsen/saj_collector#3]
Just had a new PV system installed last week. saj_collector did its job wonderfully, first time!
Only issue is when there are connectivity issues (flaky Powerline), I lose some stats, ah well.

However, saj_output_collector appears to be using generation stats off by factor 10?

> $ cd /etc && ruby /usr/local/bin/saj_output_collector
> Number of days until now for this month 26
> ...
> Energy generated 20171225: 4800 WH
> Energy generated 20171226: 13500 WH

Actuals -> see attachment

pvoutput system_id: 29573

Inverter info:
> Model: | Sununo Plus 2K
> Grid Compliance: | C10_11
> Maste Control Firmware Ver: | V1.050
> Slave Control Firmware Ver: | V1.050
> Display Board Firmware Ver: | V1.125
> Ethernet Module Firmware Ver: | V1.018

![pvoutput_29573_inverter_webpage_daily_monitoring](https://user-images.githubusercontent.com/22508603/34354960-554fe9e8-ea32-11e7-87cc-5b82c1dde9bc.png)

**Comment by jwillemsen** [comment]
Good to hear the regular capture works. Can you retrieve /day_trend.xml from your saj collector and attach it here. That is the raw output the script uses, with that I can test it here

**Comment by degerrit** [comment]
Here it is:
[day_trend.xml.txt](https://github.com/jwillemsen/saj_collector/files/1587307/day_trend.xml.txt)
No decimals, and it's not in Wh or in kWh, but in decawatts ?!

**Comment by jwillemsen** [comment]
Looks SAJ made a change in newer versions to be more precise in the day_trend.xml, attached my version, granularity is 100Wh where yours is 10Wh. Will make a change later this week to make it possible to configure the multiplication factor.

[day_trend.xml.txt](https://github.com/jwillemsen/saj_collector/files/1587356/day_trend.xml.txt)

**Comment by jwillemsen** [comment]
Looks SAJ made a change in newer versions to be more precise in the day_trend.xml, attached my version, granularity is 100Wh where yours is 10Wh. Will make a change later this week to make it possible to configure the multiplication factor.

[day_trend.xml.txt](https://github.com/jwillemsen/saj_collector/files/1587356/day_trend.xml.txt)

**Comment by jwillemsen** [comment]
I have just uploaded a new v0.5.0 release of the gem, can you install that and add the new day_trend_multiplication_factor to your yaml file with a value of 10 and trigger the script again?

**Comment by jwillemsen** [comment]
@degerrit Does the new version work with your inverter?

**Comment by degerrit** [comment]
Yep, it works - thanks.

Oddly, the day totals of my _consumption_ data is being wiped on pvoutput.org (which I can restore via more->recalculate, since the hourly data is still there). Will need to look into that. It must be related to saj_output_collector somehow, since only the data from this month is affected (and production only started December 21st, though consumption was being measured long before).

**Comment by jwillemsen** [comment]
Maybe the underlying pvoutput ruby code sends a zero, saj_output_collector only sends the energy generated

**Comment by degerrit** [comment]
I expected so. I'll check out the pvoutput code, I see it's also on github.

I guess this is the snippet that is relevant?

```
options.each do |date, values|
  puts "Energy generated #{date}: #{values[:energy_generated]} Wh"
end

pvoutput.add_batch_output(options)
```

**Comment by jwillemsen** [comment]
Yes

**Comment by degerrit** [comment]
FYI: seems like that last "consumption wiping" side-effect (of saj_output_collector) is a pvoutput.org API bug -> https://forum.pvoutput.org/t/api-post-addbatchoutput-of-generation-data-results-in-consumption-data-automatic-upload-being-zeroed/386/2

I could stick to using only _saj_output_, once my network connectovoty stabilizes with new cabling :-)
_saj_output_collector_ seems unnecessary, if _saj_output_ has already logged everything.
