### ISSUE TITLE
saj_output_collector not working anymore

### ISSUE THREAD

**Issue by jwillemsen** [jwillemsen/saj_collector#34]
pvoutput made a change that `addbatchoutput` has been deprecated and replaced by `addoutput` but batching is only possible in donation mode, see https://forum.pvoutput.org/t/changes-in-addbatchoutput-jsp-related-to-donation-mode/4461 and https://pvoutput.org/help/api_specification.html#add-output-service

**Comment by borft** [comment]
hmm, good one, I'll take a look at solax-php, to fix it. Shouldn't be too hard to do client-side batching and use the addoutput endpoint

**Comment by Wiggum127** [comment]
Experiencing SAJ integration (wired connection) no longer working since upgrade to 2021.7.

**Comment by jwillemsen** [comment]
@Wiggum127 waiting on the merge of my [PR for pvoutput](https://github.com/johnf/pvoutput/issues/26) and a new release, at that moment I can release a new saj_collector gem which fixes this.

**Comment by jwillemsen** [comment]
@Wiggum127 Updated gems are published, run `gem update saj_collector` to get the new releases, it should now work again.

**Comment by Wiggum127** [comment]
I've never used gem before. So before going down that path, for the sake of completeness, some additional info about my config:

Now running HA Docker 2021.7.1 on an up to date Raspbian (Debian Buster) and a wired SAJ converter.

relevant part of the configuration YAML looks like this:

# Adding SAJ converter
sensor:
  - platform: saj
    host: correctly populated

Given I'm using a docker installation, would the gem trick work? Or should I wait for your fix to be integrated into a next HA release?

**Comment by jwillemsen** [comment]
You are using home assistant, that has its own support for SAJ. This ruby gem is for uploading the data from the SAJ inverter to pvoutput, you can use this gem in parallel to HA, I have that setup at my side also.

I have homeassistant 2021.7.1 running with SAJ without problems, for problems with the SAJ HA support you have to contact the HA forums.

**Comment by Wiggum127** [comment]
Understood. Sorry for the confusion.

**Comment by jwillemsen** [comment]
No a problem @Wiggum127, do you have problems with showing the data of the SAJ inverter in HA itself, or the upload from HA to pvoutput?

**Comment by jwillemsen** [comment]
In my HA configuration.yml I only have this for the SAJ integration, where host is the IP address of the inverter, that works at my side

```
sensor:
  - platform: saj
    name: saj
    host: 192.168.1.24
```

**Comment by Wiggum127** [comment]
My problem is that the SAJ integration used to work (till 2021.6.2), but with the upgrade to 2021.7.0/1 the integration broke. Meaning: the entities are greyed out and don't get populated with actual values in HA. There are no errors logged.

I think the name is optional in the yml. The configuration.yml, which did not change in months, is valid.

Any pointers ?

**Comment by jwillemsen** [comment]
Yes, the `name` is optional (I have multiple sensors), no idea why that fails, it does seem to work in my setup without problems with 2021.7.0
